### ISSUE TITLE
com.samsung.android.lool

### ISSUE THREAD

**Issue by suzukar** [khlam/debloat-samsung-android#31]
If uninstall or disable com.samsung.android.lool
Will it affect Optimize battery usage and Manage battery usage?

**Comment by suzukar** [comment]
> If uninstall or disable com.samsung.android.lool Will it affect Optimize battery usage and Manage battery usage?

After testing, optimizing battery usage and managing battery usage are working properly.

**Comment by dandv** [comment]
What does that package do? (#39)
