### ISSUE TITLE
Settings app crashes

### ISSUE THREAD

**Issue by KenHV** [khlam/debloat-samsung-android#4]
The settings app crashes with a "Settings has stopped" message after opening. I ran all the commands in the list.

**Comment by khlam** [comment]
Hm, that's unfortunate. My best guess is OneUI or the keyboard app disable command was run, I thought I removed those/commented those out. You may have to do a factory reset. I haven't encountered any crashes. What device and firmware are you using? I've only tested this with S9 but it shouldn't have any problems with an S10

**Comment by KenHV** [comment]
com.android.providers.userdictionary was the dependency that got removed, restoring it works. I tested this on a J710FN (Galaxy J7 2016) with latest 8.1.0 firmware.
