### ISSUE TITLE
Debloating commands breaks dual-audio.

### ISSUE THREAD

**Issue by carafizi1** [khlam/debloat-samsung-android#46]
I'm going to investigate later, but here's a open issue
I'll link a PR later with the actual app that when uninstalled breaks support for Media Control's.

Gif just for illustration of the problem.
![image](https://github.com/khlam/debloat-samsung-android/assets/51974587/075b355e-d2cc-4cd1-b5a2-15bd55a811da)

**Comment by JesseJamez55** [comment]
Did you figure this out?

**Comment by carafizi1** [comment]
> Did you figure this out?

not yet, but it seems also that the owner of the repo is not accepting PR's as well, maybe it's an abandoned project, i'm going to fork it and i'll link here a version without this break!

Another info, in order to fix it, the best path is to revert all changes, basically run all the commands in the repo, but changing the command before the package name to:

`adb shell cmd package install-existing <package_name>`

**Comment by carafizi1** [comment]
@JesseJamez55 here is my fork: https://github.com/carafizi1/debloat-samsung-android

you can find a list of commands to copy and paste here: 
https://github.com/carafizi1/debloat-samsung-android/blob/master/revert_debloat.txt, 

this will re-add all apps and fix this issue while i cannot find the culprit package to keep the device de-bloated and dual audio working;

**Comment by carafizi1** [comment]
> Did you figure this out?

@JesseJamez55 YES!

Just re add this package and dual audio should work again!!!

`com.samsung.android.mdx.quickboard`

This package can be re-added with this command: 

`cmd package install-existing com.samsung.android.mdx.quickboard`

**Comment by carafizi1** [comment]
@khlam 
Since the maintainer of the project is not active, i've made a fork with a list of apps to debloat without breaking dual audio:
https://github.com/carafizi1/debloat-samsung-android/blob/master/debloat.txt

List of packages that break something: 
https://github.com/carafizi1/debloat-samsung-android/blob/master/do_not_remove.txt
